const SONGS = [{
  label: '小幸运',
  data: [ { level: 1, index: 3 },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 5 },
    { level: 2, index: 1 },
    { level: 2, index: 1 },
    { level: 1, index: 7 },
    { delay: true }, 
    { level: 1, index: 7 },
    { level: 1, index: 6 },
    { level: 1, index: 3 },
    { level: 1, index: 6 },
    { delay: true }, 
    { stop: true }]
}, {
    label: '地铁等待',
    data: [ 
      { level: 2, index: 3 }, 
      { level: 2, index: 4 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 2 }, 
      { level: 2, index: 2 }, 
      { level: 2, index: 5 }, 
      { delay: true }, 
      { stop: true }, 
      { stop: true }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 1 }, 
      { level: 1, index: 7 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 1 }, 
      { level: 1, index: 7 }, 
      { delay: true }, 
      { level: 2, index: 3 }, 
      { delay: true }, 
      { stop: true }, 
      { stop: true }, 
      { level: 1, index: 6 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 1 }, 
      { level: 1, index: 6 }, 
      { level: 1, index: 5 }, 
      { level: 1, index: 5 }, 
      { level: 2, index: 1 }, 
      { delay: true }, 
      { stop: true }, 
      { stop: true }, 
      { level: 2, index: 4 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 2 }, 
      { level: 2, index: 3 }, 
      { delay: true }, 
      { level: 2, index: 2 }, 
      { stop: true }, 
      { stop: true }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 2 }, 
      { delay: true }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 5 }, 
      { level: 2, index: 2 }, 
      { stop: true }, 
      { stop: true }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 1 }, 
      { level: 1, index: 7 }, 
      { delay: true }, 
      { level: 2, index: 3 }, 
      { stop: true }, 
      { stop: true }, 
      { level: 1, index: 6 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 6 }, 
      { level: 1, index: 5 }, 
      { delay: true }, 
      { level: 1, index: 6 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 2 }, 
      { level: 2, index: 3 }, 
      { stop: true }, 
      { stop: true }, 
      { level: 2, index: 4 }, 
      { level: 2, index: 3 }, 
      { level: 2, index: 1 }, 
      { level: 2, index: 2 }, 
      { delay: true }, 
      { delay: true }, 
      { stop: true } ]
}, {
  label: '爱尔兰画眉',
  data: [
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { level: 1, index: 3, duration: 3 },
    { delay: true },
    { level: 1, index: 2 },
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { delay: true },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 3 },
    { level: 1, index: 5 },
    { delay: true },
    { level: 2, index: 1 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 2 },
    { level: 1, index: 5 },
    { level: 1, index: 3 },
    { level: 1, index: 2 },
    { delay: true },
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { level: 1, index: 3, duration: 3 },
    { stop: true },
    { stop: true },
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { level: 1, index: 3, duration: 3 },
    { delay: true },
    { level: 1, index: 2 },
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { delay: true },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 3 },
    { level: 1, index: 5 },
    { delay: true },
    { level: 2, index: 1 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 2 },
    { level: 1, index: 5 },
    { level: 1, index: 3 },
    { level: 1, index: 2 },
    { delay: true },
    { level: 1, index: 1 },
    { level: 1, index: 2 },
    { level: 1, index: 1, duration: 3 },
    { stop: true },
    { stop: true },
    { level: 1, index: 5 },
    { level: 2, index: 1 },
    { delay:true },
    { level: 1, index: 7, duration: 2 },
    { level: 1, index: 5 },
    { level: 1, index: 6 },
    { delay: true },
    { level: 2, index: 1 },
    { level: 1, index: 6 },
    { level: 1, index: 7, duration: 3 },
    { level: 1, index: 5 },
    { delay: true },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6 },
    { delay: true },
    { level: 1, index: 5 },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 2 },
    { level: 2, index: 1 },
    { level: 2, index: 2 },
    { level: 2, index: 3, duration: 3 },
    { stop: true },
    { stop: true },
    { level: 1, index: 5 },
    { level: 2, index: 1 },
    { delay: true },
    { level: 1, index: 7, duration: 2 },
    { level: 1, index: 5 },
    { level: 1, index: 6 },
    { delay: true },
    { level: 2, index: 1 },
    { level: 1, index: 6 },
    { level: 1, index: 7, duration: 3 },
    { level: 1, index: 5 },
    { delay: true },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6 },
    { delay: true },
    { level: 1, index: 5 },
    { level: 1, index: 3 },
    { level: 1, index: 5 },
    { level: 1, index: 6, duration: 3 },
    { level: 2, index: 1 },
    { level: 2, index: 2 },
    { level: 2, index: 1, duration: 3 },
    { stop: true },
    { stop: true },
  ]
}]
export default SONGS 